apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docker-front-back
  name: docker-front-back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-front-back
  template:
    metadata:
      labels:
        app: docker-front-back
    spec:
      containers:
        - image: nginx:1.14.2
          name: docker-front-back
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: docker-front-back
  name: docker-front-back
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: docker-front-back
  type: LoadBalancer
