version: '3.9'
services:
  db:
    image: mongo:4.4
    container_name: db
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    networks:
      - app-network
    volumes:
      - db-volume:/data/db

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    container_name: mongo-express
    depends_on:
      - db
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_URL=mongodb://root:example@db:27017/
    networks:
      - app-network

  web:
    build: ./react-docker
    container_name: web
    volumes:
      - ./react-docker:/front-app
    ports:
      - 3000:3000
    networks:
      - app-network

  backend:
    depends_on:
      - db
    restart: unless-stopped
    build: ./backend
    container_name: back
    volumes:
     - ./backend:/back
    ports:
      - 3002:3002
    networks:
      - app-network
    command: yarn start

networks:
  app-network:
    driver: bridge

volumes:
  db-volume: